### ISSUE TITLE
Bright texture bits

### ISSUE THREAD

**Issue by Toodles2You** [pwitvoet/wadmaker#7]
![Test map](https://github.com/user-attachments/assets/f4943277-21f3-4fa1-aba5-e6c4e54f6f4c)

Bright texture bits are a cut Half-Life feature. WadMaker doesn't support them due to the palette adjustments it performs.

I only noticed this because I've been working on adding Half-Life WAD support to the `vkQuake` source port, restoring this feature in the process. I compiled a test WAD using both the HL SDK qlumpy and WadMaker.

Textures prefixed with `~` or `+[0-9/A-Z]~` were supposed to indicate that palette indices >=224 are fullbright.

I understand if you aren't interested in restoring this, since it doesn't actually work in GoldSrc.

### qlumpy
![qlumpy](https://github.com/user-attachments/assets/e8ee040a-23b5-4308-978c-b4d36506b437)
### WadMaker
![WadMaker](https://github.com/user-attachments/assets/890542ff-8a39-4e0b-990d-17f102ec9695)

### Original `~LAB1_CMP` palette
![before](https://github.com/user-attachments/assets/5ee9dbe5-7749-4091-94cb-4492bd801b63)
### Resulting WadMaker `~LAB1_CMP` palette
![after](https://github.com/user-attachments/assets/39b1d785-e935-4b73-9d10-de7adf244f12)

**Comment by pwitvoet** [comment]
One of the ideas behind WadMaker is that the user doesn't need to worry about palettes, so it just assumes that input images aren't indexed already (because hey, that's WadMaker's job!). I do plan to add a setting for using input image palettes in a future update (as well as a setting for extracting textures as 8-bit indexed images), but it's not really how WM is intended to be used.

I did investigate fullbright pixel support at some point, because it's one of the things that would be required for Quake wad support. A possible workflow would be to use fullbright mask images, so you'd have a `texturename.png` file for the normal pixels and a mostly transparent `texturename.fullbright.png` file for the fullbright pixels. When extracting textures from a wad or bsp file, `.fullbright` images would only be emitted for textures that actually contain fullbright pixels.

I suppose I could implement that and add a `-fullbrights` command-line parameter to enable this behavior.
